import Head from 'next/head'
import React, {useState, useEffect} from 'react'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Testimonials from '../../component/Testimonial'
import { Button, Stack, Container , Row, Col, Nav, Navbar, NavDropdown} from 'react-bootstrap'
import { getAllTestimonials} from '../../api-helpers/frontend/utils';


const inter = Inter({ subsets: ['latin'] })

export default function Home({testimonails}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <section >
        <Container fluid>
            <Testimonials data={testimonails}/>
        </Container>
        </section>
      </main>
    </>
  )
}


export const getServerSideProps = async () => {
  const testimonails = await getAllTestimonials();
  return {
      props: {
        testimonails,
      },
  };
};
